### ISSUE TITLE
On reboot ActiveMQ not starting on AWS instance - Red hat latest 

### ISSUE THREAD

**Issue by ganeshpachpind** [chef-cookbooks/activemq#38]
### Cookbook version

3.0.0
### Chef-client version

[]
### Platform Details
- RedHat latest - AWS
### Scenario:
- When I provision ActiveMQ cookbook on AWS cloud instance ActiveMQ service starts fine , but after reboot ActiveMQ does not start.
  Tried setup with default attributes. 

Later realized we need to add entry in systemd to be able to enable service on reboot. 

Suggestion : Modify cookbook to enable service with adding entry in Systemd

**Comment by cheeseplus** [comment]
This should be working in the 4.x cookbook as it explicitly calls enabled unless the `node['activemq']['enabled']` is set to false. Please try with the current version and open an issue if this is still present. We'll need the version of RHEL involved as well if this is the case.
